### ISSUE TITLE
elm-app: command not found

### ISSUE THREAD

**Issue by x3ro** [bjrnt/elm-feels#7]
This is probably a newbie question since I haven't done much with Elm so far, but I can't get `elm-feels` to run. `npm run api` works fine, but `npm run start` fails with 

    $ npm run start

    > elm-feels@1.0.0 start /Users/lucas/_temp/elm-feels
    > elm-app start

    sh: elm-app: command not found

**Comment by bjrnt** [comment]
Hello,

Sorry about that, seems like you're missing `create-elm-app`. You can install it with `npm install create-elm-app -g`. Let me know if you have any other questions! :)
